# -*- coding: utf-8 -*-
"""DataAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzlsbh0lvw9qOgumyPpI58KP07d5Slf2
"""

import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments
from sklearn.metrics import accuracy_score, f1_score
import numpy as np
from transformers import Trainer
from transformers import DataCollatorWithPadding
import json
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

with open("final_triplets_dataset.json", "r") as f:
    records = json.load(f)

rows = []
for r in records:
    t = r["triplets"]
    rows.append({
        "evidence_id":           r["id"],
        "supported":    t["supported"],
        "refuted":      t["refuted"]["statement"],
        "unverifiable": t["unverifiable"]["statement"]
    })

gpt4o_df = pd.DataFrame(rows)


with open("verification_sample.json", "r") as f:
    records = json.load(f)

rows = []
for r in records:
    t = r["triplets"]
    rows.append({
        "evidence_id":           r["id"],
        "supported":    t["supported"],
        "refuted":      t["refuted"]["statement"],
        "unverifiable": t["unverifiable"]["statement"]
    })

verification_df = pd.DataFrame(rows)


evidence = pd.read_csv('filtered_climate_evidence.csv')
gpt4o_df = pd.merge(gpt4o_df, evidence[['evidence_id', 'evidence_text']], how='left',
                    on='evidence_id')
verification_df = pd.merge(verification_df, evidence[['evidence_id', 'evidence_text']], how='left',
                    on='evidence_id')

# Combine human and gpt4o data
df = pd.concat([gpt4o_df, verification_df], ignore_index=True)

# Split by evidence_id BEFORE expanding
unique_evidence_ids = df['evidence_id'].unique()
train_ids, test_ids = train_test_split(
    unique_evidence_ids,
    test_size=0.1,
    random_state=42
)

train_base = df[df['evidence_id'].isin(train_ids)]
test_base = df[df['evidence_id'].isin(test_ids)]

def expand_rows(df):

    rows = []

    for _, r in df.iterrows():

        rows.append({
            "context": r["evidence_text"],
            "statement": r["supported"],
            "label": 0
        })

        rows.append({
            "context": r["evidence_text"],
            "statement": r["refuted"],
            "label": 1
        })

        rows.append({
            "context": r["evidence_text"],
            "statement": r["unverifiable"],
            "label": 2
        })

    return pd.DataFrame(rows)


train_df = expand_rows(train_base)
test_df = expand_rows(test_base)

train_df = train_df.dropna(subset=["context", "statement", "label"]).reset_index(drop=True)
test_df = test_df.dropna(subset=["context", "statement", "label"]).reset_index(drop=True)

train_df["label"] = train_df["label"].astype(int)
test_df["label"] = test_df["label"].astype(int)

print("Train label distribution:\n", train_df["label"].value_counts())
print(f"Train examples: {len(train_df)}")
print("\nTest label distribution:\n", test_df["label"].value_counts())
print(f"Test examples: {len(test_df)}")

# Shuffle to prevent ordering effects
train_df = train_df.sample(frac=1, random_state=42).reset_index(drop=True)

train_dataset = Dataset.from_pandas(train_df, preserve_index=False)
test_dataset = Dataset.from_pandas(test_df, preserve_index=False)

# Use RoBERTa instead - better for subtle differences
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(example):
    return tokenizer(
        example["context"],
        example["statement"],
        truncation=True,
        max_length=512,
        padding=False
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)
train_dataset = train_dataset.remove_columns(["context", "statement"])
test_dataset = test_dataset.remove_columns(["context", "statement"])

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=5e-6,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    num_train_epochs=3,
    eval_strategy="epoch",
    logging_dir="./logs",
    logging_steps=100,
    warmup_steps=100,
    weight_decay=0.01,
    max_grad_norm=1.0,
    metric_for_best_model="f1"
)

def compute_metrics(eval_pred):

    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    cm = confusion_matrix(labels, preds)

    print("Confusion Matrix:")
    print(cm)

    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="macro")
    }

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    data_collator=data_collator
)

trainer.train()

trainer.evaluate()

